export const message = {
  CREATE_SUCCESS: 'Created successfully',
  GET_DETAILS: 'Get details successfully',
  UPDATE_SUCCESS: 'Data update successfully',
  DELETE_SUCCESS: 'Delete successfully',
  VALIDATION_FAIL: 'Validation failed',
  INTERNAL_SERVER_ERROR: 'Internal server error',

  auth: {
    CREATE_SUCCESS: 'User Created Successfully',
    INVALID_CREDENTIALS: 'Invalid credentials',
    LOGOUT_SUCCESS: 'Logout successfully',
    LOGIN_SUCCESS: 'Login successfully',
    INVALID_PASSWORD: 'Invalid password',
    INVALID_USER: 'Invalid user',
    NOT_AUTHORIZED: 'Only admin can access this page',
    GET_DETAILS: 'Get details successfully',
  },
  ingredient: {
    INGREDIENT_LIST: 'Ingredient fetch successfully',
    INGREDIENT_DELETE: 'Ingredient deleted successfully',
    INGREDIENT_UPDATED: 'Ingredient updated successfully',
    INGREDIENT_CREATED: 'Ingredient created successfully',
  },
  packagingMaterial: {
    MATERIAL_PACKAGING_LIST: 'Material packaging fetch successfully',
    MATERIAL_PACKAGING_DELETE: 'Material packaging deleted successfully',
    MATERIAL_PACKAGING_UPDATED: 'Material packaging updated successfully',
    MATERIAL_PACKAGING_CREATED: 'Material packaging created successfully',
    GET_MATERIAL_PACKAGING_DETAIL: 'Get Material packaging detail successfully',
  },

  supplier: {
    SUPPLIER_DELETED: 'Supplier deleted successfully',
    SUPPLIER_LIST: 'Supplier fetch successfully',
    SUPPLIER_UPDATED: 'Supplier updated successfully',
    SUPPLIER_CREATED: 'Supplier created successfully',
  },
  recipe: {
    RECIPE_LIST: 'Recipe fetch successfully',
    RECIPE_DELETE: 'Recipe deleted successfully',
    RECIPE_UPDATED: 'Recipe updated successfully',
    RECIPE_CREATED: 'Recipe created successfully',
    RECIPE_DUPLICATE_CREATED: 'Recipe duplicated successfully',
    RECIPE_DUPLICATE_ERROR: 'No Such Recipe Existed!',
    RECIPE_PRICE_ERROR: 'Please Put Price Before Making Live!',
  },
  vendor_kitchen: {
    DUMP_CSV_EXPORT: 'Dump recipes exported to vendor kitchen CSV successfully',
    DUMP_CSV_NOT_FOUND: 'No dump recipes found for the given date(s)',
  },
  recipe_menu: {
    RECIPE_LIST: 'Recipe-Menu fetch successfully',
    RECIPE_DUPLICATE: 'Recipe-Menu duplicated successfully',
    RECIPE_DELETE: 'Recipe-Menu deleted successfully',
    RECIPE_UPDATED: 'Recipe-Menu updated successfully',
    RECIPE_CREATED: 'Recipe-Menu created successfully',
    RECIPE_LIVE: 'Recipe-Menu live successfully',
    RECIPE_STEPPERS: 'Recipe-Menu Stepper Data Fetched Successfully',
    RECIPE_REPORTS: 'AutoSelection Report Fetched Successfully',
    RECIPE_AUTO_SEL_PROGRESS: 'Recipe-Menu Auto Selection Inprogress',
    RECIPE_NOTIFICATION_PROGRESS: 'Recipe-Menu Auto Selection Inprogress',
    RECIPE_MRD_COUNT: 'Count For Dates Fetched Successfully',
    RECIPE_NOTIFICATION: 'Recipe-Menu Notification Send Started Successfully',
    RECIPE_AUTO_SEL: 'Recipe-Menu Auto Selection Started Successfully',
    RECIPE_DUMP: 'Recipe-Menu dumped successfully',
    RECIPE_DUMP_INSUFFICIENT_VARIANT: 'Please Check Menu!',
    RECIPE_DUMP_MENU: 'Please Select Menu!',
    RECIPE_DUMP_INSUFFICIENT_MENU:
      'Please Select Alteast 3 Breakfast, 3 Meal & 3 Snack In Menu!',
    RECIPE_DUMP_MISSING_PACKAGING_MATERIAL:
      'Packaging material is missing for variant. Please ensure at least one packaging material is assigned to components in portioning_balance.',
    RECIPE_DUPLICATE_ERROR: 'No Such Recipe Existed!',
  },
  component: {
    COMPONENT_LIST: 'Component fetch successfully',
    COMPONENT_VALID_ID: 'Please Enter Valid Component Id!',
    COMPONENT_DELETE: 'Component deleted successfully',
    COMPONENT_UPDATED: 'Component updated successfully',
    COMPONENT_CREATED: 'Component created successfully',
    COMPONENT_DUPLICATE_CREATED: 'Recipe duplicated successfully',
    SUBRECIPE_DUPLICATE_CREATED: 'Recipe duplicated successfully',
    COMPONENT_DUPLICATE_ERROR: 'No Such Component/SubRecipe Existed!',
  },
  sub_recipe: {
    SUB_RECIPE_LIST: 'Sub-Recipe fetch successfully',
    SUB_RECIPE_VALID_ID: 'Please Enter Valid Sub Recipe Id!',
    SUB_RECIPE_DELETE: 'Sub-Recipe deleted successfully',
    SUB_RECIPE_UPDATED: 'Sub-Recipe updated successfully',
    SUB_RECIPE_CREATED: 'Sub-Recipe created successfully',
  },
  history: {
    HISTORY_CREATED: 'create',
    HISTORY_UPDATE: 'update',
    HISTORY_REPLACE: 'replace',
    HISTORY_DELETE: 'delete',

    HISTORY_LIST: 'History list fetched successfully!',
  },
  library: {
    IMAGE_LIST: 'Image fetch successfully',
    IMAGE_DELETE: 'Image deleted successfully',
    IMAGE_UPLOAD: 'Image upload successfully',
  },
  kitchen_app: {
    GET_PROTEIN_TYPE: 'Protein type get Successfully',
    GET_KITCHEN_RECIPE_LIST: 'kitchen Recipe get Successfully',
    GET_KITCHEN_PORTINING: 'Kitchen porting fetch successfully',
    UPDATE_KITCHEN_PORTINING: 'Kitchen porting update successfully',
  },
  customers: {
    CUSTOMER_LIST_FETCH: 'Customer List Fetched Successfully!',
    COOLER_BAG: 'Cooler Bag Updated!',
    BAG_BOX: 'Bag/Box Updated!',
  },
  chef_allocation: {
    CHEF_ALLOCATION_FROM_MENU: 'Allocation created Successfully!',
    CHECK_CHEF_ALLOCATION_FROM_MENU: 'Allocation Allready created!',
    CHECK_CHEF_ALLOCATION_REMAIN: 'Ready for Allocation!',
    CHEF_ALLOCATION_ALLREADY_MENU_CREATED:
      'Allocation Allready created Successfully!',
    CHEF_ALLOCATION_WEEKLY: 'Weekly Allocation created Successfully!',
    CHEF_ALLOCATION_CHEF_LIST: 'get Chef list successfully!',
    CHEF_ALLOCATION_NOTIFICATION: 'Notification send successfully!',
  },
  survey: {
    SURVEY_DATA: 'survey details fetch successfully',
    SURVEY_LIST: 'survey list fetch successfully',
  },
  arabyads: {
    ARABYADSDATA: 'Araby ads list fetched successfully',
  },
};
